import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // escolha os pesos que vai usar
  variable: "--font-poppins",          // cria uma variável CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
       <html lang="pt-br" className={`${poppins.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
